# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llm.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'llm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tllm.proto\x12\x03llm\",\n\x0b\x43hatMessage\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"M\n\x0b\x43hatRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12.\n\x14\x63onversation_history\x18\x02 \x03(\x0b\x32\x10.llm.ChatMessage\"\x99\x01\n\tChatEvent\x12&\n\x04type\x18\x01 \x01(\x0e\x32\x18.llm.ChatEvent.EventType\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x12\n\nerror_code\x18\x03 \x01(\t\x12\x15\n\rerror_message\x18\x04 \x01(\t\"+\n\tEventType\x12\t\n\x05\x43HUNK\x10\x00\x12\x08\n\x04\x44ONE\x10\x01\x12\t\n\x05\x45RROR\x10\x02\"\x0f\n\rHealthRequest\";\n\x0eHealthResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x18\n\x10ollama_reachable\x18\x02 \x01(\x08\x32s\n\x07LLMChat\x12\x30\n\nStreamChat\x12\x10.llm.ChatRequest\x1a\x0e.llm.ChatEvent0\x01\x12\x36\n\x0bHealthCheck\x12\x12.llm.HealthRequest\x1a\x13.llm.HealthResponseB.Z,github.com/mugen64/bibi-core/internal/llm/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,github.com/mugen64/bibi-core/internal/llm/pb'
  _globals['_CHATMESSAGE']._serialized_start=18
  _globals['_CHATMESSAGE']._serialized_end=62
  _globals['_CHATREQUEST']._serialized_start=64
  _globals['_CHATREQUEST']._serialized_end=141
  _globals['_CHATEVENT']._serialized_start=144
  _globals['_CHATEVENT']._serialized_end=297
  _globals['_CHATEVENT_EVENTTYPE']._serialized_start=254
  _globals['_CHATEVENT_EVENTTYPE']._serialized_end=297
  _globals['_HEALTHREQUEST']._serialized_start=299
  _globals['_HEALTHREQUEST']._serialized_end=314
  _globals['_HEALTHRESPONSE']._serialized_start=316
  _globals['_HEALTHRESPONSE']._serialized_end=375
  _globals['_LLMCHAT']._serialized_start=377
  _globals['_LLMCHAT']._serialized_end=492
# @@protoc_insertion_point(module_scope)
