// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: llm.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatEvent_EventType int32

const (
	ChatEvent_CHUNK ChatEvent_EventType = 0
	ChatEvent_DONE  ChatEvent_EventType = 1
	ChatEvent_ERROR ChatEvent_EventType = 2
)

// Enum value maps for ChatEvent_EventType.
var (
	ChatEvent_EventType_name = map[int32]string{
		0: "CHUNK",
		1: "DONE",
		2: "ERROR",
	}
	ChatEvent_EventType_value = map[string]int32{
		"CHUNK": 0,
		"DONE":  1,
		"ERROR": 2,
	}
)

func (x ChatEvent_EventType) Enum() *ChatEvent_EventType {
	p := new(ChatEvent_EventType)
	*p = x
	return p
}

func (x ChatEvent_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatEvent_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_llm_proto_enumTypes[0].Descriptor()
}

func (ChatEvent_EventType) Type() protoreflect.EnumType {
	return &file_llm_proto_enumTypes[0]
}

func (x ChatEvent_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatEvent_EventType.Descriptor instead.
func (ChatEvent_EventType) EnumDescriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{2, 0}
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"` // "user" | "assistant"
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_llm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ChatRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Prompt              string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	ConversationHistory []*ChatMessage         `protobuf:"bytes,2,rep,name=conversation_history,json=conversationHistory,proto3" json:"conversation_history,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_llm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{1}
}

func (x *ChatRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *ChatRequest) GetConversationHistory() []*ChatMessage {
	if x != nil {
		return x.ConversationHistory
	}
	return nil
}

type ChatEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ChatEvent_EventType    `protobuf:"varint,1,opt,name=type,proto3,enum=llm.ChatEvent_EventType" json:"type,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatEvent) Reset() {
	*x = ChatEvent{}
	mi := &file_llm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatEvent) ProtoMessage() {}

func (x *ChatEvent) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatEvent.ProtoReflect.Descriptor instead.
func (*ChatEvent) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{2}
}

func (x *ChatEvent) GetType() ChatEvent_EventType {
	if x != nil {
		return x.Type
	}
	return ChatEvent_CHUNK
}

func (x *ChatEvent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ChatEvent) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ChatEvent) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_llm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{3}
}

type HealthResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Healthy         bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	OllamaReachable bool                   `protobuf:"varint,2,opt,name=ollama_reachable,json=ollamaReachable,proto3" json:"ollama_reachable,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_llm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{4}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetOllamaReachable() bool {
	if x != nil {
		return x.OllamaReachable
	}
	return false
}

var File_llm_proto protoreflect.FileDescriptor

const file_llm_proto_rawDesc = "" +
	"\n" +
	"\tllm.proto\x12\x03llm\";\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"j\n" +
	"\vChatRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12C\n" +
	"\x14conversation_history\x18\x02 \x03(\v2\x10.llm.ChatMessageR\x13conversationHistory\"\xbe\x01\n" +
	"\tChatEvent\x12,\n" +
	"\x04type\x18\x01 \x01(\x0e2\x18.llm.ChatEvent.EventTypeR\x04type\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"+\n" +
	"\tEventType\x12\t\n" +
	"\x05CHUNK\x10\x00\x12\b\n" +
	"\x04DONE\x10\x01\x12\t\n" +
	"\x05ERROR\x10\x02\"\x0f\n" +
	"\rHealthRequest\"U\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12)\n" +
	"\x10ollama_reachable\x18\x02 \x01(\bR\x0follamaReachable2s\n" +
	"\aLLMChat\x120\n" +
	"\n" +
	"StreamChat\x12\x10.llm.ChatRequest\x1a\x0e.llm.ChatEvent0\x01\x126\n" +
	"\vHealthCheck\x12\x12.llm.HealthRequest\x1a\x13.llm.HealthResponseB.Z,github.com/mugen64/bibi-core/internal/llm/pbb\x06proto3"

var (
	file_llm_proto_rawDescOnce sync.Once
	file_llm_proto_rawDescData []byte
)

func file_llm_proto_rawDescGZIP() []byte {
	file_llm_proto_rawDescOnce.Do(func() {
		file_llm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llm_proto_rawDesc), len(file_llm_proto_rawDesc)))
	})
	return file_llm_proto_rawDescData
}

var file_llm_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_llm_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_llm_proto_goTypes = []any{
	(ChatEvent_EventType)(0), // 0: llm.ChatEvent.EventType
	(*ChatMessage)(nil),      // 1: llm.ChatMessage
	(*ChatRequest)(nil),      // 2: llm.ChatRequest
	(*ChatEvent)(nil),        // 3: llm.ChatEvent
	(*HealthRequest)(nil),    // 4: llm.HealthRequest
	(*HealthResponse)(nil),   // 5: llm.HealthResponse
}
var file_llm_proto_depIdxs = []int32{
	1, // 0: llm.ChatRequest.conversation_history:type_name -> llm.ChatMessage
	0, // 1: llm.ChatEvent.type:type_name -> llm.ChatEvent.EventType
	2, // 2: llm.LLMChat.StreamChat:input_type -> llm.ChatRequest
	4, // 3: llm.LLMChat.HealthCheck:input_type -> llm.HealthRequest
	3, // 4: llm.LLMChat.StreamChat:output_type -> llm.ChatEvent
	5, // 5: llm.LLMChat.HealthCheck:output_type -> llm.HealthResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_llm_proto_init() }
func file_llm_proto_init() {
	if File_llm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llm_proto_rawDesc), len(file_llm_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_llm_proto_goTypes,
		DependencyIndexes: file_llm_proto_depIdxs,
		EnumInfos:         file_llm_proto_enumTypes,
		MessageInfos:      file_llm_proto_msgTypes,
	}.Build()
	File_llm_proto = out.File
	file_llm_proto_goTypes = nil
	file_llm_proto_depIdxs = nil
}
