// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: llm.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LLMChat_StreamChat_FullMethodName  = "/llm.LLMChat/StreamChat"
	LLMChat_HealthCheck_FullMethodName = "/llm.LLMChat/HealthCheck"
)

// LLMChatClient is the client API for LLMChat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LLMChatClient interface {
	// -server-streaming client sends one request that is answered by a stream
	StreamChat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatEvent], error)
	HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type lLMChatClient struct {
	cc grpc.ClientConnInterface
}

func NewLLMChatClient(cc grpc.ClientConnInterface) LLMChatClient {
	return &lLMChatClient{cc}
}

func (c *lLMChatClient) StreamChat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LLMChat_ServiceDesc.Streams[0], LLMChat_StreamChat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatRequest, ChatEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LLMChat_StreamChatClient = grpc.ServerStreamingClient[ChatEvent]

func (c *lLMChatClient) HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, LLMChat_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LLMChatServer is the server API for LLMChat service.
// All implementations must embed UnimplementedLLMChatServer
// for forward compatibility.
type LLMChatServer interface {
	// -server-streaming client sends one request that is answered by a stream
	StreamChat(*ChatRequest, grpc.ServerStreamingServer[ChatEvent]) error
	HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedLLMChatServer()
}

// UnimplementedLLMChatServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLLMChatServer struct{}

func (UnimplementedLLMChatServer) StreamChat(*ChatRequest, grpc.ServerStreamingServer[ChatEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamChat not implemented")
}
func (UnimplementedLLMChatServer) HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedLLMChatServer) mustEmbedUnimplementedLLMChatServer() {}
func (UnimplementedLLMChatServer) testEmbeddedByValue()                 {}

// UnsafeLLMChatServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LLMChatServer will
// result in compilation errors.
type UnsafeLLMChatServer interface {
	mustEmbedUnimplementedLLMChatServer()
}

func RegisterLLMChatServer(s grpc.ServiceRegistrar, srv LLMChatServer) {
	// If the following call panics, it indicates UnimplementedLLMChatServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LLMChat_ServiceDesc, srv)
}

func _LLMChat_StreamChat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LLMChatServer).StreamChat(m, &grpc.GenericServerStream[ChatRequest, ChatEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LLMChat_StreamChatServer = grpc.ServerStreamingServer[ChatEvent]

func _LLMChat_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMChatServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMChat_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMChatServer).HealthCheck(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LLMChat_ServiceDesc is the grpc.ServiceDesc for LLMChat service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LLMChat_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "llm.LLMChat",
	HandlerType: (*LLMChatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _LLMChat_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamChat",
			Handler:       _LLMChat_StreamChat_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "llm.proto",
}
