// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: tts.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TextToSpeech_StreamSynthesize_FullMethodName = "/tts.TextToSpeech/StreamSynthesize"
	TextToSpeech_HealthCheck_FullMethodName      = "/tts.TextToSpeech/HealthCheck"
)

// TextToSpeechClient is the client API for TextToSpeech service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TextToSpeechClient interface {
	// Unary request (text in), streaming response (audio chunks out) -
	// same shape as LLM's StreamChat: one input, no need for the client
	// to send more once the request is issued.
	StreamSynthesize(ctx context.Context, in *SynthesizeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AudioChunkMsg], error)
	HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type textToSpeechClient struct {
	cc grpc.ClientConnInterface
}

func NewTextToSpeechClient(cc grpc.ClientConnInterface) TextToSpeechClient {
	return &textToSpeechClient{cc}
}

func (c *textToSpeechClient) StreamSynthesize(ctx context.Context, in *SynthesizeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AudioChunkMsg], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TextToSpeech_ServiceDesc.Streams[0], TextToSpeech_StreamSynthesize_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SynthesizeRequest, AudioChunkMsg]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TextToSpeech_StreamSynthesizeClient = grpc.ServerStreamingClient[AudioChunkMsg]

func (c *textToSpeechClient) HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, TextToSpeech_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TextToSpeechServer is the server API for TextToSpeech service.
// All implementations must embed UnimplementedTextToSpeechServer
// for forward compatibility.
type TextToSpeechServer interface {
	// Unary request (text in), streaming response (audio chunks out) -
	// same shape as LLM's StreamChat: one input, no need for the client
	// to send more once the request is issued.
	StreamSynthesize(*SynthesizeRequest, grpc.ServerStreamingServer[AudioChunkMsg]) error
	HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedTextToSpeechServer()
}

// UnimplementedTextToSpeechServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTextToSpeechServer struct{}

func (UnimplementedTextToSpeechServer) StreamSynthesize(*SynthesizeRequest, grpc.ServerStreamingServer[AudioChunkMsg]) error {
	return status.Error(codes.Unimplemented, "method StreamSynthesize not implemented")
}
func (UnimplementedTextToSpeechServer) HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedTextToSpeechServer) mustEmbedUnimplementedTextToSpeechServer() {}
func (UnimplementedTextToSpeechServer) testEmbeddedByValue()                      {}

// UnsafeTextToSpeechServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TextToSpeechServer will
// result in compilation errors.
type UnsafeTextToSpeechServer interface {
	mustEmbedUnimplementedTextToSpeechServer()
}

func RegisterTextToSpeechServer(s grpc.ServiceRegistrar, srv TextToSpeechServer) {
	// If the following call panics, it indicates UnimplementedTextToSpeechServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TextToSpeech_ServiceDesc, srv)
}

func _TextToSpeech_StreamSynthesize_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SynthesizeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TextToSpeechServer).StreamSynthesize(m, &grpc.GenericServerStream[SynthesizeRequest, AudioChunkMsg]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TextToSpeech_StreamSynthesizeServer = grpc.ServerStreamingServer[AudioChunkMsg]

func _TextToSpeech_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TextToSpeechServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TextToSpeech_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TextToSpeechServer).HealthCheck(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TextToSpeech_ServiceDesc is the grpc.ServiceDesc for TextToSpeech service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TextToSpeech_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tts.TextToSpeech",
	HandlerType: (*TextToSpeechServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _TextToSpeech_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSynthesize",
			Handler:       _TextToSpeech_StreamSynthesize_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "tts.proto",
}
