# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stt.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'stt.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tstt.proto\x12\x03stt\"t\n\rAudioChunkMsg\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\x12\x10\n\x08\x63hannels\x18\x03 \x01(\x05\x12\x14\n\x0csample_width\x18\x04 \x01(\x05\x12\x18\n\x10\x65nd_of_utterance\x18\x05 \x01(\x08\"d\n\x14TranscriptSegmentMsg\x12\x10\n\x08start_ms\x18\x01 \x01(\x05\x12\x0e\n\x06\x65nd_ms\x18\x02 \x01(\x05\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x12\n\x05score\x18\x04 \x01(\x02H\x00\x88\x01\x01\x42\x08\n\x06_score\"\xe3\x01\n\x0fTranscriptEvent\x12,\n\x04type\x18\x01 \x01(\x0e\x32\x1e.stt.TranscriptEvent.EventType\x12+\n\x08segments\x18\x02 \x03(\x0b\x32\x19.stt.TranscriptSegmentMsg\x12\x11\n\x04lang\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x12\n\nerror_code\x18\x04 \x01(\t\x12\x15\n\rerror_message\x18\x05 \x01(\t\".\n\tEventType\x12\x0b\n\x07PARTIAL\x10\x00\x12\t\n\x05\x46INAL\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x42\x07\n\x05_lang\"\x0f\n\rHealthRequest\"7\n\x0eHealthResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x14\n\x0cmodel_loaded\x18\x02 \x01(\t2\x88\x01\n\x0cSpeechToText\x12@\n\x10StreamTranscribe\x12\x12.stt.AudioChunkMsg\x1a\x14.stt.TranscriptEvent(\x01\x30\x01\x12\x36\n\x0bHealthCheck\x12\x12.stt.HealthRequest\x1a\x13.stt.HealthResponseB.Z,github.com/mugen64/bibi-core/internal/stt/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stt_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,github.com/mugen64/bibi-core/internal/stt/pb'
  _globals['_AUDIOCHUNKMSG']._serialized_start=18
  _globals['_AUDIOCHUNKMSG']._serialized_end=134
  _globals['_TRANSCRIPTSEGMENTMSG']._serialized_start=136
  _globals['_TRANSCRIPTSEGMENTMSG']._serialized_end=236
  _globals['_TRANSCRIPTEVENT']._serialized_start=239
  _globals['_TRANSCRIPTEVENT']._serialized_end=466
  _globals['_TRANSCRIPTEVENT_EVENTTYPE']._serialized_start=411
  _globals['_TRANSCRIPTEVENT_EVENTTYPE']._serialized_end=457
  _globals['_HEALTHREQUEST']._serialized_start=468
  _globals['_HEALTHREQUEST']._serialized_end=483
  _globals['_HEALTHRESPONSE']._serialized_start=485
  _globals['_HEALTHRESPONSE']._serialized_end=540
  _globals['_SPEECHTOTEXT']._serialized_start=543
  _globals['_SPEECHTOTEXT']._serialized_end=679
# @@protoc_insertion_point(module_scope)
