// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: stt.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TranscriptEvent_EventType int32

const (
	TranscriptEvent_PARTIAL TranscriptEvent_EventType = 0
	TranscriptEvent_FINAL   TranscriptEvent_EventType = 1
	TranscriptEvent_ERROR   TranscriptEvent_EventType = 2
)

// Enum value maps for TranscriptEvent_EventType.
var (
	TranscriptEvent_EventType_name = map[int32]string{
		0: "PARTIAL",
		1: "FINAL",
		2: "ERROR",
	}
	TranscriptEvent_EventType_value = map[string]int32{
		"PARTIAL": 0,
		"FINAL":   1,
		"ERROR":   2,
	}
)

func (x TranscriptEvent_EventType) Enum() *TranscriptEvent_EventType {
	p := new(TranscriptEvent_EventType)
	*p = x
	return p
}

func (x TranscriptEvent_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TranscriptEvent_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_stt_proto_enumTypes[0].Descriptor()
}

func (TranscriptEvent_EventType) Type() protoreflect.EnumType {
	return &file_stt_proto_enumTypes[0]
}

func (x TranscriptEvent_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TranscriptEvent_EventType.Descriptor instead.
func (TranscriptEvent_EventType) EnumDescriptor() ([]byte, []int) {
	return file_stt_proto_rawDescGZIP(), []int{2, 0}
}

type AudioChunkMsg struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Data           []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	SampleRate     int32                  `protobuf:"varint,2,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	Channels       int32                  `protobuf:"varint,3,opt,name=channels,proto3" json:"channels,omitempty"`
	SampleWidth    int32                  `protobuf:"varint,4,opt,name=sample_width,json=sampleWidth,proto3" json:"sample_width,omitempty"`
	EndOfUtterance bool                   `protobuf:"varint,5,opt,name=end_of_utterance,json=endOfUtterance,proto3" json:"end_of_utterance,omitempty"` // client sets true on the final chunk of an utterance
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AudioChunkMsg) Reset() {
	*x = AudioChunkMsg{}
	mi := &file_stt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunkMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunkMsg) ProtoMessage() {}

func (x *AudioChunkMsg) ProtoReflect() protoreflect.Message {
	mi := &file_stt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChunkMsg.ProtoReflect.Descriptor instead.
func (*AudioChunkMsg) Descriptor() ([]byte, []int) {
	return file_stt_proto_rawDescGZIP(), []int{0}
}

func (x *AudioChunkMsg) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AudioChunkMsg) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *AudioChunkMsg) GetChannels() int32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

func (x *AudioChunkMsg) GetSampleWidth() int32 {
	if x != nil {
		return x.SampleWidth
	}
	return 0
}

func (x *AudioChunkMsg) GetEndOfUtterance() bool {
	if x != nil {
		return x.EndOfUtterance
	}
	return false
}

type TranscriptSegmentMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartMs       int32                  `protobuf:"varint,1,opt,name=start_ms,json=startMs,proto3" json:"start_ms,omitempty"`
	EndMs         int32                  `protobuf:"varint,2,opt,name=end_ms,json=endMs,proto3" json:"end_ms,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Score         *float32               `protobuf:"fixed32,4,opt,name=score,proto3,oneof" json:"score,omitempty"` // matches score: float | None
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscriptSegmentMsg) Reset() {
	*x = TranscriptSegmentMsg{}
	mi := &file_stt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscriptSegmentMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscriptSegmentMsg) ProtoMessage() {}

func (x *TranscriptSegmentMsg) ProtoReflect() protoreflect.Message {
	mi := &file_stt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscriptSegmentMsg.ProtoReflect.Descriptor instead.
func (*TranscriptSegmentMsg) Descriptor() ([]byte, []int) {
	return file_stt_proto_rawDescGZIP(), []int{1}
}

func (x *TranscriptSegmentMsg) GetStartMs() int32 {
	if x != nil {
		return x.StartMs
	}
	return 0
}

func (x *TranscriptSegmentMsg) GetEndMs() int32 {
	if x != nil {
		return x.EndMs
	}
	return 0
}

func (x *TranscriptSegmentMsg) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TranscriptSegmentMsg) GetScore() float32 {
	if x != nil && x.Score != nil {
		return *x.Score
	}
	return 0
}

type TranscriptEvent struct {
	state    protoimpl.MessageState    `protogen:"open.v1"`
	Type     TranscriptEvent_EventType `protobuf:"varint,1,opt,name=type,proto3,enum=stt.TranscriptEvent_EventType" json:"type,omitempty"`
	Segments []*TranscriptSegmentMsg   `protobuf:"bytes,2,rep,name=segments,proto3" json:"segments,omitempty"`
	Lang     *string                   `protobuf:"bytes,3,opt,name=lang,proto3,oneof" json:"lang,omitempty"`
	// populated only when type == ERROR
	ErrorCode     string `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscriptEvent) Reset() {
	*x = TranscriptEvent{}
	mi := &file_stt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscriptEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscriptEvent) ProtoMessage() {}

func (x *TranscriptEvent) ProtoReflect() protoreflect.Message {
	mi := &file_stt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscriptEvent.ProtoReflect.Descriptor instead.
func (*TranscriptEvent) Descriptor() ([]byte, []int) {
	return file_stt_proto_rawDescGZIP(), []int{2}
}

func (x *TranscriptEvent) GetType() TranscriptEvent_EventType {
	if x != nil {
		return x.Type
	}
	return TranscriptEvent_PARTIAL
}

func (x *TranscriptEvent) GetSegments() []*TranscriptSegmentMsg {
	if x != nil {
		return x.Segments
	}
	return nil
}

func (x *TranscriptEvent) GetLang() string {
	if x != nil && x.Lang != nil {
		return *x.Lang
	}
	return ""
}

func (x *TranscriptEvent) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *TranscriptEvent) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_stt_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stt_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_stt_proto_rawDescGZIP(), []int{3}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	ModelLoaded   string                 `protobuf:"bytes,2,opt,name=model_loaded,json=modelLoaded,proto3" json:"model_loaded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_stt_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stt_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_stt_proto_rawDescGZIP(), []int{4}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetModelLoaded() string {
	if x != nil {
		return x.ModelLoaded
	}
	return ""
}

var File_stt_proto protoreflect.FileDescriptor

const file_stt_proto_rawDesc = "" +
	"\n" +
	"\tstt.proto\x12\x03stt\"\xad\x01\n" +
	"\rAudioChunkMsg\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1f\n" +
	"\vsample_rate\x18\x02 \x01(\x05R\n" +
	"sampleRate\x12\x1a\n" +
	"\bchannels\x18\x03 \x01(\x05R\bchannels\x12!\n" +
	"\fsample_width\x18\x04 \x01(\x05R\vsampleWidth\x12(\n" +
	"\x10end_of_utterance\x18\x05 \x01(\bR\x0eendOfUtterance\"\x81\x01\n" +
	"\x14TranscriptSegmentMsg\x12\x19\n" +
	"\bstart_ms\x18\x01 \x01(\x05R\astartMs\x12\x15\n" +
	"\x06end_ms\x18\x02 \x01(\x05R\x05endMs\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x19\n" +
	"\x05score\x18\x04 \x01(\x02H\x00R\x05score\x88\x01\x01B\b\n" +
	"\x06_score\"\x92\x02\n" +
	"\x0fTranscriptEvent\x122\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1e.stt.TranscriptEvent.EventTypeR\x04type\x125\n" +
	"\bsegments\x18\x02 \x03(\v2\x19.stt.TranscriptSegmentMsgR\bsegments\x12\x17\n" +
	"\x04lang\x18\x03 \x01(\tH\x00R\x04lang\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\".\n" +
	"\tEventType\x12\v\n" +
	"\aPARTIAL\x10\x00\x12\t\n" +
	"\x05FINAL\x10\x01\x12\t\n" +
	"\x05ERROR\x10\x02B\a\n" +
	"\x05_lang\"\x0f\n" +
	"\rHealthRequest\"M\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12!\n" +
	"\fmodel_loaded\x18\x02 \x01(\tR\vmodelLoaded2\x88\x01\n" +
	"\fSpeechToText\x12@\n" +
	"\x10StreamTranscribe\x12\x12.stt.AudioChunkMsg\x1a\x14.stt.TranscriptEvent(\x010\x01\x126\n" +
	"\vHealthCheck\x12\x12.stt.HealthRequest\x1a\x13.stt.HealthResponseB.Z,github.com/mugen64/bibi-core/internal/stt/pbb\x06proto3"

var (
	file_stt_proto_rawDescOnce sync.Once
	file_stt_proto_rawDescData []byte
)

func file_stt_proto_rawDescGZIP() []byte {
	file_stt_proto_rawDescOnce.Do(func() {
		file_stt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stt_proto_rawDesc), len(file_stt_proto_rawDesc)))
	})
	return file_stt_proto_rawDescData
}

var file_stt_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_stt_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_stt_proto_goTypes = []any{
	(TranscriptEvent_EventType)(0), // 0: stt.TranscriptEvent.EventType
	(*AudioChunkMsg)(nil),          // 1: stt.AudioChunkMsg
	(*TranscriptSegmentMsg)(nil),   // 2: stt.TranscriptSegmentMsg
	(*TranscriptEvent)(nil),        // 3: stt.TranscriptEvent
	(*HealthRequest)(nil),          // 4: stt.HealthRequest
	(*HealthResponse)(nil),         // 5: stt.HealthResponse
}
var file_stt_proto_depIdxs = []int32{
	0, // 0: stt.TranscriptEvent.type:type_name -> stt.TranscriptEvent.EventType
	2, // 1: stt.TranscriptEvent.segments:type_name -> stt.TranscriptSegmentMsg
	1, // 2: stt.SpeechToText.StreamTranscribe:input_type -> stt.AudioChunkMsg
	4, // 3: stt.SpeechToText.HealthCheck:input_type -> stt.HealthRequest
	3, // 4: stt.SpeechToText.StreamTranscribe:output_type -> stt.TranscriptEvent
	5, // 5: stt.SpeechToText.HealthCheck:output_type -> stt.HealthResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_stt_proto_init() }
func file_stt_proto_init() {
	if File_stt_proto != nil {
		return
	}
	file_stt_proto_msgTypes[1].OneofWrappers = []any{}
	file_stt_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stt_proto_rawDesc), len(file_stt_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stt_proto_goTypes,
		DependencyIndexes: file_stt_proto_depIdxs,
		EnumInfos:         file_stt_proto_enumTypes,
		MessageInfos:      file_stt_proto_msgTypes,
	}.Build()
	File_stt_proto = out.File
	file_stt_proto_goTypes = nil
	file_stt_proto_depIdxs = nil
}
