# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import tts_pb2 as tts__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tts_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TextToSpeechStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamSynthesize = channel.unary_stream(
                '/tts.TextToSpeech/StreamSynthesize',
                request_serializer=tts__pb2.SynthesizeRequest.SerializeToString,
                response_deserializer=tts__pb2.AudioChunkMsg.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/tts.TextToSpeech/HealthCheck',
                request_serializer=tts__pb2.HealthRequest.SerializeToString,
                response_deserializer=tts__pb2.HealthResponse.FromString,
                _registered_method=True)


class TextToSpeechServicer:
    """Missing associated documentation comment in .proto file."""

    def StreamSynthesize(self, request, context):
        """Unary request (text in), streaming response (audio chunks out) -
        same shape as LLM's StreamChat: one input, no need for the client
        to send more once the request is issued.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TextToSpeechServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamSynthesize': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamSynthesize,
                    request_deserializer=tts__pb2.SynthesizeRequest.FromString,
                    response_serializer=tts__pb2.AudioChunkMsg.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=tts__pb2.HealthRequest.FromString,
                    response_serializer=tts__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tts.TextToSpeech', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tts.TextToSpeech', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TextToSpeech:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamSynthesize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tts.TextToSpeech/StreamSynthesize',
            tts__pb2.SynthesizeRequest.SerializeToString,
            tts__pb2.AudioChunkMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tts.TextToSpeech/HealthCheck',
            tts__pb2.HealthRequest.SerializeToString,
            tts__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
